server:
  port: 9000

logging:
  level:
    org:
      springframework:
        security: DEBUG
#    root: INFO
#    org.springframework.web: INFO
#    org.springframework.security: INFO
#    org.springframework.security.oauth2: INFO


spring:
  main:
    banner-mode: off
