server:
  port: 8080

logging:
    level:
      org:
        springframework:
          security: DEBUG

spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: "http://auth-server:9000"

